version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: social-credit-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: social-credit-bot
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - social-credit-network

  bot:
    build: .
    container_name: social-credit-bot
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/social-credit-bot
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - social-credit-network
    volumes:
      - ./logs:/app/logs

volumes:
  mongodb_data:

networks:
  social-credit-network:
    driver: bridge